### ISSUE TITLE
TOPページに確認用modalを作成

### ISSUE THREAD

**Issue by shigeek** [kazuya002ex/philo#2]
- [x] モーダル作成
- [x] 色々なサイズのpdfを格納可能に

**Comment by holasoynaoki** [comment]
## やったこと
modalの作成
modalのシンプルな機能

modal参考↓
https://tcd-theme.com/2021/08/javascript-modalwindow.html

## これからやること

- [ ] 命名の改善
- [ ] PDFを様々なサイズで対応できるようにする(iflame)

**Comment by kazuya002ex** [comment]
実装を確認したため、close
